e_datamining<-function(explaining=0){

if(explaining==0) {
cat("\014")
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## git, devtools, usethis 명령문 -------\033[0m ", '\n')
cat("git add .  ", '\n')
cat("git commit -m  ''first commit''  ", '\n')
cat("git push origin main 또는 master  ", '\n')
cat("  ", '\n')
cat("devtools::install_github('ssbaj/aj412s2')  ", '\n')
cat("  ", '\n')
cat("list.files() ", '\n')
cat("getwd() ", '\n')
cat("setwd('c:/dataPy') ", '\n')
cat("setwd('c:\\\\dataPy')", '\n')
cat("  ", '\n')
cat("usethis::use_data(데이터셋)", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;32m## seq 와 rep 명령문 -------\033[0m ", '\n')
cat("#\033[1;33m 처음 숫자는 100, 마지막 숫자는 200, 총 자료수는 20개인 자료 \033[0m", '\n')
cat("  seq(100, 200, (200-100)/(20-1))  # 100부터 시작해서 200까지, 총 자료수는 20개 ", '\n')
cat("#\033[1;32m seq(1:5)을 3회 반복한 자료  \033[0m", '\n')
cat("  rep(seq(1:5), 3) ", '\n')
cat("  ", '\n')
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## for 문: R vs Python -------\033[0m ", '\n')
cat("  for(i in 1:10) { cat(i, '\\n') }  # R명령문 ", '\n')
cat("  ", '\n')
cat("  for i in range(1, 11):  # Python명령문 ", '\n')
cat("       print(i, 'hellow', 'world', '\\n') ", '\n')
cat("  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## 화면 스크롤 갯수 확대 -------\033[0m ", '\n')
cat("  print(df, max=99999)  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## rowSums 및 rowMeans --------- \033[0m ", '\n')
cat("  Adata$check<-\033[1;33mrowSums\033[0m(Adata[, c(3:4)], na.rm=T)   ", '\n')
cat("  Adata$check<-\033[1;33mrowMeans\033[0m(Adata[, c(3:4)], na.rm=T)   ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## dplyr사용법 -------  \033[0m ", '\n')
cat("  ", '\n')
cat("  df <- BasicData %>% \033[1;36mmutate\033[0m(gm.satprice = satprice-mean(satprice, na.rm=T),   ", '\n')
cat("                             새변수 = paste(광역자치, 기초자치, sep = '_' ),  ", '\n')
cat("                             gm.conv = conv-mean(conv, na.rm=T))  ", '\n')
cat("  ", '\n')
cat("  df$brand_se <- \033[1;36mrecode\033[0m(df$brand, 'old값1' = 'new값1', 'old값2' = 'new값2') ", '\n')
cat("  ", '\n')
cat("  df %>% \033[1;36mgroup_by\033[0m(브랜드)   ", '\n')
cat("      %>% \033[1;36msummarize\033[0m(편의성평균=mean(편의성, na.rm=T), 표준편차=sd(편의성, na.rm=T), 자료수=n())   ", '\n')
cat("  ", '\n')
cat("  df %>% \033[1;36mselect\033[0m(브랜드, 편의성)  ", '\n')
cat("  ", '\n')
cat("  df %>% \033[1;36mfilter\033[0m(변수E==2015 & (변수F=='C' | 변수F=='G') )  ", '\n')
cat("  df %>% \033[1;36mfilter\033[0m( grepl('상현동', 시군구) & grepl('상떼빌', 단지명)) ", '\n')
cat("  ", '\n')
cat("  df %>% \033[1;36marrange\033[0m(연령대, 성별)  또는, df %>% \033[1;36marrange\033[0m(desc(연령대), 성별)  ", '\n')
cat("  ", '\n')
cat("  df <- \033[1;36mrename\033[0m(df, 새변수명1=old변수명1, 새변수명2=old변수명2)  ", '\n')
cat("  또는, colnames(df)[1]<-c('새변수명')  ", '\n')
cat("  ", '\n')
cat("  \033[1;36mmerge\033[0m(data1, data2, by='id')  ", '\n')
cat("     %>% \033[1;36mmerge\033[0m(data3, by='id')  ", '\n')
cat("     ", '\n')
cat("  \033[1;36mmerge\033[0m(data1, \033[1;36mselect\033[0m(data2, -c(v3) ) , by='id')  ", '\n')
cat("     %>% \033[1;36mmerge\033[0m(data3, by='index', all=T)  ", '\n')
cat("  ", '\n')
cat("  df<-df %>% \033[1;36mrelocate\033[0m(자산, .before = 소득)", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## tidyr사용법 I(CASE1) -------  \033[0m ", '\n')
cat("   ", '\n')
cat("  # Example DATA  ", '\n')
cat("  df<-matrix(1:15, nrow=3, byrow=T) ", '\n')
cat("  df<-data.frame(df) ", '\n')
cat("  colnames(df)<-c('구분ID', 'Q1', 'Q2', 'Q3', 'Q4') ", '\n')
cat("  df[1,1]<-'A1'; df[2,1]<-'A2'; df[3,1]<-'A3' ", '\n')
cat("  df ", '\n')
cat("   ", '\n')
cat("  # long format으로 변경 ", '\n')
cat("  library(tidyverse) ", '\n')
cat("  df_long <- df %>% pivot_longer(cols=2:5) ", '\n')
cat("  colnames(df_long)<-c('구분ID', 'Quarter', 'Value') ", '\n')
cat("  df_long ", '\n')
cat("   ", '\n')
cat("  # wide format으로 변경 ", '\n')
cat("  df_wide <- df_long %>% pivot_wider(  ", '\n')
cat("      names_from = Quarter,     # 어떤 열을 새 열로 만들 것인지   ", '\n')
cat("      values_from = Value       # 어떤 값을 채워 넣을 것인지   ", '\n')
cat("    ) ", '\n')
cat("  df_wide ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## tidyr사용법 I(CASE2) -------  \033[0m ", '\n')
cat("   ", '\n')
cat("  library(tidyr); library(dplyr)  ", '\n')
cat("  df <- tibble(  ", '\n')
cat("    id = c(1:3),  ", '\n')
cat("    math_score = c(90, 85, 88),  ", '\n')
cat("    english_score = c(80, 78, 92)  ", '\n')
cat("    )  ", '\n')
cat("    ", '\n')
cat("  df_long <- df %>%  ", '\n')
cat("    pivot_longer(  ", '\n')
cat("      cols = ends_with('score'),   # 변환할 열 선택 ", '\n')
cat("      names_to = 'subject',        # 새 변수 이름 (열 이름이 값으로 감) ", '\n')
cat("      values_to = 'score'          # 새 변수 값 ", '\n')
cat("    ) ", '\n')
cat("   ", '\n')
cat("  df_wide <- df_long %>% ", '\n')
cat("    pivot_wider( ", '\n')
cat("      names_from = subject,     # 어떤 열을 새 열로 만들 것인지 ", '\n')
cat("      values_from = score       # 어떤 값을 채워 넣을 것인지 ", '\n')
cat("    ) ", '\n')
cat("   ", '\n')
cat("\033[1;33m## tidyr사용법 II -------  \033[0m ", '\n')
cat("   library(tidyr); library(dplyr)   ", '\n')
cat("   data1 <- data %>% mutate(새변수 = paste(V1, V2, sep = '_' ) )  ", '\n')
cat("   data2 <- data1 %>% select(새변수, V1, V2, V3, V4) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## colnames() : 변수명 바꾸기 -----  \033[0m ", '\n')
cat("   df<-data.frame(     ", '\n')
cat("        V1=c(1,2,3,1,2,3),     ", '\n')
cat("        V2=c(23,45,32,NA,56,76),     ", '\n')
cat("        V3=c(1,NA,1,1,2,1)     ", '\n')
cat("        )     ", '\n')
cat("   colnames(df)<-c('index', 'age', 'gender')  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## complete.cases() : NA미싱데이터 삭제하기 ---- \033[0m ", '\n')
cat("  df<-df[complete.cases(df), ]  ", '\n')
cat("  df<-df[complete.cases(df$conv, df$satprice), ]  ", '\n')
cat("  df<-comp22(df) ", '\n')
cat("  df<-comp22(df, conv, satprice) ", '\n')
cat("  ", '\n')
cat("\033[1;33m## 변수를 선택해서 새 데이터셋으로 만들기 ---- \033[0m ", '\n')
cat("  새데이터셋 <- df[ , c(2, 3, 4:6)] ", '\n') # 변수 순서를 지정해 선택함
cat("  새데이터셋 <- df %>% select(brand, year, month:age) ", '\n') # 변수 순서를 지정해 선택함
cat("  새데이터셋 <- sel22(df, id, dept, brand, age ) ", '\n')
cat("  또는... ", '\n')
cat("  index <- c(1, 2, 3, 9)  ", '\n')
cat("  새데이터셋 <- df[ , index]  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## 변수의 속성을 한꺼번에 변경하기 ------- \033[0m ", '\n')
cat("  index <- c(7, 8, 9, 11)  ", '\n')
cat("  New_df <- lapply(df[, index], as.numeric)  ", '\n')
cat("  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## NA미싱데이터 자료수 확인1 ------- \033[0m ", '\n')
cat("  sum(is.na(df$age))  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## NA미싱데이터 자료수 확인2 -------  \033[0m ", '\n')
cat("  library(aj412s)  ", '\n')
cat("  na_col(df)  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## 변수의 속성 ------- \033[0m ", '\n')
cat("  class_col(df)  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## 변수명 변경 ------- \033[0m ", '\n')
cat("  library(aj412s2)  ", '\n')
cat("  colnames(df)<-c('id','brand','conv','satprice','age','gender')  ", '\n')
cat("  colnames(df)[6]<-c('성별')  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## index변수 만들기 -------  \033[0m ", '\n')
cat("  df <- mkindex(df)  ", '\n')
cat("  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## 더미변수 만들기 ------- \033[0m ", '\n')
cat("\033[1;33m # 방법1 --- \033[0m ", '\n')
cat("  library(aj412s)  ", '\n')
cat("  df<-BasicData  ", '\n')
cat("    ", '\n')
cat("  unique(df$conv)   ", '\n')
cat("  # conv의 변수값: 3 NA  2  1  4  5  ", '\n')
cat("  ", '\n')
cat("  df$dum1<-0; df$dum2<-0; df$dum3<-0; df$dum4<-0; df$dum5<-0  ", '\n')
cat("  for(i in 1:n) {  ", '\n')
cat("      if( is.na(df$conv[i]) ) { next }  ", '\n')
cat("      else if( df$conv[i] == 1 ) {df$dum1[i]<-1}  ", '\n')
cat("      else if( df$conv[i] == 2 ) {df$dum2[i]<-1}  ", '\n')
cat("      else if( df$conv[i] == 3 ) {df$dum3[i]<-1}  ", '\n')
cat("      else if( df$conv[i] == 4 ) {df$dum4[i]<-1}  ", '\n')
cat("      else if( df$conv[i] == 5 ) {df$dum5[i]<-1}  ", '\n')
cat("   }  ", '\n')
cat("  ", '\n')
cat("\033[1;33m # 방법2 --- \033[0m ", '\n')
cat("  library(aj412s2)  ", '\n')
cat("  df<-BasicData  ", '\n')
cat("  df<-comp22(df)  ", '\n')
cat("  df<-mkdum(df, conv)  ", '\n')
cat("  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## Grouping변수 만들기 ------- \033[0m ", '\n')
cat("  cn<-quantile(df$expend, c(.25, .5, .75) , na.rm=T)  ", '\n')
cat("  df<-mkgroup(df, expend, cn)  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## 결과의 저장 -------  \033[0m ", '\n')
cat("  sink('결과저장.txt')   ", '\n')
cat("    ……   ", '\n')
cat("  sink()   ", '\n')
cat("  ", '\n')
cat("\033[1;33m## aggegate 명령문 ---------- \033[0m ", '\n')
cat("  aggregate(가격만족도 ~ 브랜드, 데이터셋, FUN = mean)  ", '\n')
cat("  aggregate(satprice~gender, subset(df, gender==1), 자료수length 또는 평균mean 또는 표준편차sd ", '\n')
cat("  ", '\n')
cat("\033[1;33m## subset 명령문 ---------- \033[0m ", '\n')
cat("  \033[1;36msubset\033[0m(df, brand=='KIA', select=c(brand, age))  ", '\n')
cat("  Newdf <- \033[1;36msubset\033[0m(df, \033[1;36mgrepl\033[0m('KIA', df$brand) , \033[1;36mselect\033[0m=c(brand, conv, satprice))  ", '\n')
cat("  ", '\n')
cat("  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## table사용법 --------------  \033[0m ", '\n')
cat("  table를 사용해 막대그래프 그리기  ", '\n')
cat("  table(df$gender, df$brand)   ", '\n')
cat("  barplot(\033[1;34mtable\033[0m(df$gender, df$brand), beside=T, horiz=F, ylab='빈도수')   ", '\n')
cat("  ", '\n')
cat("\033[1;33m## dplyr의 filter명령문 대신 자료를 솎아내서 새데이터셋 만들기 ------- \033[0m ", '\n')
cat("  df2 <- df[ df$debtratio !=Inf ,  ]  ", '\n')
cat("  df2 <- df[ !is.na(df$debtratio) ,  ]  ", '\n')
cat("  df2 <- df[ df$debtratio <= 124 ,  ]  ", '\n')
cat("  df2 <- df[ complete.cases(df) ,  ]   ", '\n')
cat("  df2 <- df[ complete.cases(df$편의성, df$가격만족, df$연령대) ,  ]   ", '\n')
cat("  ", '\n')
cat("\033[1;33m## 코드값 재코딩 -------  \033[0m ", '\n')
cat("  df$편의성2[df$conv==5] <- 4  ", '\n')
cat("  df$성별2[df$gender==2] <- 0  ", '\n')
cat("  df[df==''] <- NA   ", '\n')
cat("  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## 데이터프레임 -------\033[0m ", '\n')
cat("  df<-data.frame(  ", '\n')
cat("     id=c(1, 2, 3, 4, 5, 6, 7, 8),  ", '\n')
cat("     day=c('Mon', 'Mon', 'Tue', 'Tue', 'Tue', 'Wed', 'Wed', 'Wed'),  ", '\n')
cat("     gender=c('남','여','여','남','남','여','남','여'),  ", '\n')
cat("     expend=c(800, 1400, 2000, 1600, 1400, 1600, 1340, 1900),  ", '\n')
cat("     no.items=c(4, 3, 5, 10, 13, 6, 22, 9)  )  ", '\n')
cat("   ", '\n')
cat("  df[ ,-c(1,3)]  ", '\n')
cat("  df[df$gender=='남', ]  ", '\n')
cat("  df[df$gender=='남', c(2, 3)]  ", '\n')
cat("  df[df$id>=3, c(2, 3)]  ", '\n')
cat("   ", '\n')
cat("\033[1;32m  rowSums(df[,c(4:5)])  \033[0m ", '\n')
cat("\033[1;32m  rowMeans(df[,c(4:5)])  \033[0m ", '\n')
cat("\033[1;32m  colSums(df[,c(4:5)])  \033[0m ", '\n')
cat("\033[1;32m  colMeans(df[,c(4:5)])  \033[0m ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("\033[1;33m## 변수 설명을 추가하는 방법... ------- \033[0m ", '\n')
cat("  library(Hmisc) ", '\n')
cat("  label(df$id) <- '피조사자 ID' ", '\n')
cat("  label(df$gender) <- '성별' ", '\n')
cat("  label(df$income) <- '소득' ", '\n')
cat("   ", '\n')
cat("\033[1;33m## 벡터 -------\033[0m ", '\n')
cat("  x1<-c(1:10, 14, 21:24)", '\n')
cat("  x2<-rep(8, 5)", '\n')
cat("  x3<-rep(1:3, 2) ", '\n')
cat("  x4<-seq(1, 10, 0.5) ", '\n')
cat("  x4[x4>3] ", '\n')
cat("   ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## 팩터 ------- \033[0m ", '\n')
cat("  df<-data.frame(  ", '\n')
cat("     id=c(1,2,3,4),  ", '\n')
cat("     gender=c('1','1','2','2'),  ", '\n')
cat("     income=c(2000, 2300, 4500, 4000)  )  ", '\n')
cat("   ", '\n')
cat("  df$gender2<-factor(df$gender, levels=c(1, 2), labels=c('남', '여'))  ", '\n')
cat("   ", '\n')
cat("\033[1;33m## 0을 팩터로 지정하면... ------- \033[0m ", '\n')
cat("  범주형변수는 factor로 지정한다. 단, 숫자의 경우 0을 ", '\n')
cat("  factor로 변경하고 다시 숫자numeric으로 바꾸면 0은 1이 된다 ", '\n')
cat("  x<-c(0,1,2) ", '\n')
cat("  y<-as.factor(x) ", '\n')
cat("  as.numeric(y) ", '\n')
cat("  [1] 1 2 3 ", '\n')
cat("   ", '\n')
cat("\033[1;33m## Multionomial Logit(다항로짓)의 base 지정 ------- \033[0m ", '\n')
cat("\033[1;33m   base 지정을 하려면 종속변수를 factor로 지정  \033[0m ", '\n')
cat("  df$debt3<-as.factor(df$debt3) ", '\n')
cat("  df$debt3 <- relevel(df$debt3, ref = 'collateral')  # 기준 범주(Base)는 부채가 collateral인 케이스   ", '\n')
cat("   ", '\n')
cat("\033[1;33m## 리스트 -------\033[0m ", '\n')
cat("  x<-rep(1:3, 3)  ", '\n')
cat("  df<-data.frame(  ", '\n')
cat("     id=c(1,2,3,4),  ", '\n')
cat("     gender=c('1','1','2','2'),  ", '\n')
cat("     income=c(2000, 2300, 4500, 4000)  )  ", '\n')
cat("  datalist<-list(x, df)  ", '\n')
cat("  datalist[[1]]  ", '\n')
cat("  datalist[[2]]$income  ", '\n')
cat("   ", '\n')
cat("\033[1;33m## 행렬 -------\033[0m ", '\n')
cat("  x<-matrix(1:9, nrow=3, byrow=T) ", '\n')
cat("  x[1,3]", '\n')
cat("  ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;33m## csv 데이터파일 로딩하기 ----- \033[0m ", '\n')
cat("  library(aj412s2)  ", '\n')
cat("  df<-opencsv(df55.csv)  ", '\n')
cat("  df<-read.csv('df55.csv')  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## 데이터셋에 한글 변수명이 있을 경우 ----- \033[0m ", '\n')
cat("  df<-opencsv(df55.csv)  ", '\n')
cat("  df<-read.csv('df55.csv', fileEncoding='CP949', encoding='UTF-8')  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## csv 데이터파일 저장하기 -----  \033[0m ", '\n')
cat("  write.csv(df, 'ABC.csv')  ", '\n')
cat("  write.csv(df, 'ABC.csv', fileEncoding='EUC-KR' ) # Qgis로 불러오는 csv파일 만들기", '\n')
cat("  ", '\n')
cat("\033[1;33m## Excel 데이터파일 로딩하기 ----- \033[0m ", '\n')
cat("  df<-openxlsx(df88.xlsx)  ", '\n')
cat("  ", '\n')
cat("  library(readxl)  ", '\n')
cat("  df<-read_xlsx('df88.xlsx')  ", '\n')
cat("  ", '\n')
cat("\033[1;33m## TXT 데이터파일 로딩하기 ----- \033[0m ", '\n')
cat("  df <- read.table('젠트리지수.txt',   ", '\n')
cat("            header = TRUE,    # 첫 행이 변수명인 경우 TRUE  ", '\n')
cat("            sep = '|',        # 구분자를 | 로 지정  ", '\n')
cat("            stringsAsFactors = FALSE,   ", '\n')
cat("            fileEncoding = 'UTF-8')  # 한글 인코딩 문제 방지  ", '\n')
cat("    ", '\n')
cat("\033[1;33m## Excel 데이터파일 저장하기 -----  \033[0m ", '\n')
cat("  library(writexl)  ", '\n')
cat("  write_xlsx(df, '아무거나.xlsx')  ", '\n')
cat("  ", '\n')
cat("  ", '\n')
} }

