e_datamining<-function(explaining=0){

if(explaining==0) {
cat("\014")
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("\033[1;31m## 화면 스크롤 갯수 확대 -------\033[0m ", '\n')
cat("  ", '\n')
cat("## 화면 스크롤 옵션 -----  ", '\n')
cat("  df<-as.data.frame(df)  ", '\n')
cat("  print(df, max=99999)  ", '\n')
cat("  ", '\n')
cat("## csv 데이터파일 로딩하기 -----  ", '\n')
cat("  library(aj412s2)  ", '\n')
cat("  df<-opencsv(df55.csv)  ", '\n')
cat("  df<-read.csv('df55.csv')  ", '\n')
cat("  ", '\n')
cat("## 데이터셋에 한글 변수명이 있을 경우 -----  ", '\n')
cat("  df<-opencsv(df55.csv)  ", '\n')
cat("  df<-read.csv('df55.csv', fileEncoding='CP949', encoding='UTF-8')  ", '\n')
cat("  ", '\n')
cat("## csv 데이터파일 저장하기 -----  ", '\n')
cat("  write.csv(df, 'ABC.csv')  ", '\n')
cat("  ", '\n')
cat("## Excel 데이터파일 로딩하기 -----  ", '\n')
cat("  df<-openxlsx(df88.xlsx)  ", '\n')
cat("  ", '\n')
cat("  library(readxl)  ", '\n')
cat("  df<-read_xlsx('df88.xlsx')  ", '\n')
cat("  ", '\n')
cat("## Excel 데이터파일 저장하기 -----  ", '\n')
cat("  library(writexl)  ", '\n')
cat("  write_xlsx(df, '아무거나.xlsx')  ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("\014")
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("## colnames() : 변수명 바꾸기 -----  ", '\n')
cat("   df<-data.frame(     ", '\n')
cat("   V1=c(1,2,3,1,2,3),     ", '\n')
cat("   V2=c(23,45,32,NA,56,76),     ", '\n')
cat("   V3=c(1,NA,1,1,2,1))     ", '\n')
cat("   colnames(df)<-c('index', 'age', 'gender')  ", '\n')
cat("  ", '\n')
cat("## complete.cases() : NA미싱데이터 삭제하기 ----  ", '\n')
cat("  df<-comp22(df) ", '\n')
cat("  df<-comp22(df, conv, satprice) ", '\n')
cat("  df<-df[complete.cases(df), ]  ", '\n')
cat("  df<-df[complete.cases(df$conv, df$satprice), ]  ", '\n')
cat("  ", '\n')
cat("## 변수를 선택해서 새 데이터셋으로 만들기 ----  ", '\n')
cat("  새데이터셋 <- sel22(df, id, dept, brand, age ", '\n')
cat("  또는... ", '\n')
cat("  index <- c(1, 2, 3, 9)  ", '\n')
cat("  새데이터셋 <- df[ , index]  ", '\n')
cat("  ", '\n')
cat("## 변수의 속성을 한꺼번에 변경하기 -------  ", '\n')
cat("  index <- c(7, 8, 9, 11)  ", '\n')
cat("  New_df <- lapply(df[, index], as.numeric)  ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("\014")
cat("\033[1;34m**************************************************************** \033[0m ", '\n')

cat("## NA미싱데이터 자료수 확인1 -------  ", '\n')
cat("  sum(is.na(df$age))  ", '\n')
cat("  ", '\n')
cat("## NA미싱데이터 자료수 확인2 -------  ", '\n')
cat("  library(aj412s)  ", '\n')
cat("  na_col(df)  ", '\n')
cat("## 변수의 속성 -------  ", '\n')
cat("  class_col(df)  ", '\n')
cat("  ", '\n')
cat("## 변수명 변경 -------  ", '\n')
cat("  library(aj412s2)  ", '\n')
cat("  colnames(df)<-c('id','brand','conv','satprice','age','gender')  ", '\n')
cat("  colnames(df)[6]<-c('성별')  ", '\n')
cat("  ", '\n')
cat("## index변수 만들기 -------  ", '\n')
cat("  df <- mkindex(df)  ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("\014")
cat("\033[1;34m**************************************************************** \033[0m ", '\n')

cat("## 더미변수 만들기 -------  ", '\n')
cat("# 방법1  ", '\n')
cat("  library(aj412s2)  ", '\n')
cat("  df<-BasicData  ", '\n')
cat("  df<-comp22(df)  ", '\n')
cat("  df<-mkdum(df, conv)  ", '\n')
cat("  ", '\n')
cat("# 방법2  ", '\n')
cat("  library(aj412s)  ", '\n')
cat("  df<-BasicData  ", '\n')
cat("    ", '\n')
cat("  unique(df$conv)   ", '\n')
cat("  # conv의 변수값: 3 NA  2  1  4  5  ", '\n')
cat("  ", '\n')
cat("  df$dum1<-0; df$dum2<-0; df$dum3<-0; df$dum4<-0; df$dum5<-0  ", '\n')
cat("  for(i in 1:n) {  ", '\n')
cat("      if( is.na(df$conv[i]) ) { next }  ", '\n')
cat("      else if( df$conv[i] == 1 ) {df$dum1[i]<-1}  ", '\n')
cat("      else if( df$conv[i] == 2 ) {df$dum2[i]<-1}  ", '\n')
cat("      else if( df$conv[i] == 3 ) {df$dum3[i]<-1}  ", '\n')
cat("      else if( df$conv[i] == 4 ) {df$dum4[i]<-1}  ", '\n')
cat("      else if( df$conv[i] == 5 ) {df$dum5[i]<-1}  ", '\n')
cat("   }  ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("\014")
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("## Grouping변수 만들기 -------  ", '\n')
cat("  cn<-quantile(df$expend, c(.25, .5, .75) , na.rm=T)  ", '\n')
cat("  df<-mkgroup(df, expend, cn)  ", '\n')
cat("  ", '\n')
cat("## 결과의 저장 -------  ", '\n')
cat("  sink('결과저장.txt')   ", '\n')
cat("    ……   ", '\n')
cat("  sink()   ", '\n')
cat("  ", '\n')
cat("# aggegate 명령문 ---------- ", '\n')
cat("  aggregate(가격만족도 ~ 브랜드, 데이터셋, FUN = mean)  ", '\n')
cat("  aggregate(satprice~gender, subset(df, gender==1), 자료수length 또는 평균mean 또는 표준편차sd ", '\n')
cat("  ", '\n')
cat("# subset 명령문 ---------- ", '\n')
cat("  subset(데이터셋 , 조건 또는 조건 생략, select=c(변수1, 변수2))  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("\014")
cat("\033[1;34m**************************************************************** \033[0m ", '\n')

cat("## table사용법 --------------  ", '\n')
cat("  table를 사용해 막대그래프 그리기  ", '\n')
cat("  table(df$gender, df$brand)   ", '\n')
cat("  barplot(table(df$gender, df$brand), beside=T, horiz=F, ylab='빈도수')   ", '\n')
cat("  ", '\n')
cat("## rowSums 및 rowMeans ---------  ", '\n')
cat("  Adata$check<-rowSums(Adata[, c(3:4)], na.rm=T)   ", '\n')
cat("  Adata$check<-rowMeans(Adata[, c(3:4)], na.rm=T)   ", '\n')
cat("  ", '\n')
cat("## dplyr의 filter명령문 대신 자료를 솎아내서 새데이터셋 만들기 -------  ", '\n')
cat("  df2 <- df[ df$debtratio !=Inf ,  ]  ", '\n')
cat("  df2 <- df[ !is.na(df$debtratio) ,  ]  ", '\n')
cat("  df2 <- df[ df$debtratio <= 124 ,  ]  ", '\n')
cat("  df2 <- df[ complete.cases(df) ,  ]   ", '\n')
cat("  df2 <- df[ complete.cases(df$편의성, df$가격만족, df$연령대) ,  ]   ", '\n')
cat("  ", '\n')
cat("## 코드값 재코딩 -------  ", '\n')
cat("  df$편의성2[df$conv==5] <- 4  ", '\n')
cat("  df$성별2[df$gender==2] <- 0  ", '\n')
cat("  df[df==''] <- NA   ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("\014")
cat("\033[1;34m**************************************************************** \033[0m ", '\n')
cat("## dplyr사용법 -------  ", '\n')
cat("  ", '\n')
cat("  df %>% group_by(브랜드)   ", '\n')
cat("      %>% summarize(편의성평균=mean(편의성, na.rm=T), 표준편차=sd(편의성, na.rm=T), 자료수=n())   ", '\n')
cat("  ", '\n')
cat("  df %>% select(브랜드, 편의성)  ", '\n')
cat("  ", '\n')
cat("  df %>% filter(변수E==2015 & (변수F=='C' | 변수F=='G') )  ", '\n')
cat("  ", '\n')
cat("  df %>% arrange(연령대, 성별)  또는, df %>% arrange(desc(연령대), 성별)  ", '\n')
cat("  ", '\n')
cat("  df <- rename(df, 새변수명1=old변수명1, 새변수명2=old변수명2)  ", '\n')
cat("  또는, colnames(df)[1]<-c('새변수명')  ", '\n')
cat("  ", '\n')
cat("  merge(data1, data2, by='id')  ", '\n')
cat("     %>% merge(data3, by='id')  ", '\n')
cat("     ", '\n')
cat("  merge(data1, select(data2, -c(v3) ) , by='id')  ", '\n')
cat("     %>% merge(data3, by='index', all=T)  ", '\n')
cat("  ", '\n')
cat("  df <- BasicData %>% mutate(gm.satprice = satprice-mean(satprice, na.rm=T),   ", '\n')
cat("                             gm.conv = conv-mean(conv, na.rm=T))  ", '\n')
cat(" ", '\n')
} }

