e_dplyr<-function(explaining=0){

if(explaining==0) {
cat("  ", '\n')
cat("\033[1;31m## dplyr사용법1 ------------------ \033[0m", '\n')
cat("   ", '\n')
cat("  df %>% group_by(브랜드) %>% summarize(편의성평균=mean(conv,na.rm=T), 자료수=n(), .groups='drop_last') ", '\n')
cat("   ", '\n')
cat("  df$brand_se <- recode(df$brand , 'old1' = 'new1', 'old2' = 'new2')) \033[1;32m# recode는 파이프 명령문 사용X \033[0m ", '\n')
cat("   ", '\n')
cat("  NewDataset <- df %>% select(브랜드, 성별) ", '\n')
cat("   ", '\n')  
cat("  NewDataset <- merge(data1, data2, by='id')  ", '\n')
cat("                      %>% merge(data3, by='id')  ", '\n')
cat("     ", '\n')
cat("  NewDataset <- merge(data1, select(data2, -c(v3) ) , by='id')  ", '\n')
cat("                      %>% merge(data3, by='index')  ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m## df$시군구 변수에서 용인수지구 단어가 있는 레코드를 솎아내기 ------ \033[0m", '\n')
cat("  df%>%filter( grepl('용인수지구' , df$시군구)) ", '\n')
cat("   ", '\n')
cat("\033[1;31m## 상현동 아파트들 중 상떼빌 아파트만 솎아내기 ------\033[0m ", '\n')
cat("  df%>%filter( grepl('상현동', df$시군구) & grepl('상떼빌', df$단지명)) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("\033[1;31m## dplyr사용법3 -------------- \033[0m", '\n')
cat("  df<-df %>% arrange(연령대, 성별) ", '\n')
cat("  df<-df %>% arrange(desc(연령대), 성별, 브랜드) ", '\n')
cat("   ", '\n')
cat("  df<-df %>% relocate(브랜드, .before=성별) ", '\n')
cat("  df<-df %>% relocate(브랜드, .after=성별) ", '\n')
cat("  ", '\n')
cat("  df <- BasicData %>% mutate(gm.satprice = satprice-mean(satprice, na.rm=T),   ", '\n')
cat("                             gm.conv = conv-mean(conv, na.rm=T))  ", '\n')
cat("  ", '\n')
cat("  df<-rename(df, 새변수명=편의성) #rename대신 colnames(df)[컬럼번호]가 더 편리함", '\n')
cat("  ", '\n')
cat(" # aggegate vs. group_by() summarize() ", '\n')
cat("   aggregate(가격만족도 ~ 브랜드, data = 데이터셋, FUN = mean) ", '\n')
cat("   데이터셋 %>% group_by(브랜드) %>% summarize(mean(가격만족도, na.rm=T)) ", '\n')
cat("   ", '\n')
cat("   new_df$addr<-paste0(new_df$시군구, ' ', new_df$번지) ", '\n')
cat("   new_df$거래금액만원 <- gsub('\\,', '', new_df$거래금액만원) ", '\n')
cat("   new_df$거래금액만원 <- as.numeric(new_df$거래금액만원) ", '\n')
cat("    ", '\n')
cat("   new_df2 <- new_df %>% group_by(addr) %>% ", '\n')
cat("     summarize( 평균거래금액만원 = mean(거래금액만원, na.rm = TRUE),    ", '\n')
cat("                건물명 = first(건물명),   # 그룹 내 동일한 값   ", '\n')
cat("                addr = first(addr),   # 그룹 내 동일한 값 ", '\n')
cat("                주택유형 = first(주택유형),   # 그룹 내 동일한 값  ", '\n') 
cat("                건축년도 = first(건축년도), ", '\n')
cat("                거래수 = n(), ", '\n')
cat("                long_x = first(long_x), ", '\n')
cat("                lat_y = first(lat_y), ", '\n')
cat("                .groups = 'drop' # 그룹 해제   ", '\n')
cat("              )   ", '\n')
cat("   ", '\n')
} 
}

