e_graph<-function(explaining=0){

if(explaining==0) {

cat("\033[1;31m # 나만의 theme 만들기 -------------------\033[0m ", '\n')
cat(" library(ggplot2)  ", '\n')
cat(" mytheme<-theme( ", '\n')
cat("   plot.background = element_rect(fill = 'white', color = 'black', linewidth = 1), # 전체 플롯배경: '#843E3D1C'  ", '\n')
cat("   panel.background = element_rect(fill = 'white', color = 'gray'), # 그래프 영역 배경 색", '\n')
cat("   panel.grid.major = element_line(color = '#0300031C', linewidth = 0.5), # 주요 그리드 선  ", '\n')
cat("   panel.grid.minor = element_line(color = 'gray', linewidth = 0.25, linetype = 'dashed'), # 보조 그리드 선  ", '\n')
cat("   panel.grid = element_line(color = 'gray', linewidth = 0.5), # 전체 그리드 선 색과 두께  ", '\n')
cat("   axis.title.x = element_text(size = 20, color = 'black', hjust=0.5), # X축 제목 스타일", '\n')
cat("   axis.title.y = element_text(size = 20, color = 'black', hjust=0.5), # Y축 제목 스타일", '\n')
cat("   axis.text.x = element_text(size = 13, color = 'black', hjust=0.5), # X축 제목 스타일", '\n')
cat("   axis.text.y = element_text(size = 13, color = 'black', hjust=0.5), # Y축 제목 스타일", '\n')
cat("   plot.title = element_text(size = 20, color = 'black', hjust = 0, vjust = 2, face = 'bold'), # Title 조정", '\n')
cat("   plot.margin = margin(t = 20, r = 10, b = 10, l = 10), # Title 조정", '\n')
cat("   legend.text = element_text(size = 10),", '\n')
cat("   legend.title = element_text(size = 10),", '\n')
cat("   legend.position = 'right'  ## legend.position = 'none' OR 'bottom'", '\n')
cat(" )  ", '\n')
cat("   ", '\n')
cat("\033[1;32m mycols(.81, .63, .20) #노랑색 \033[0m ", '\n')
cat("\033[1;32m mycols(.60, .16, .16) #가넷색 \033[0m ", '\n')
cat("\033[1;32m mycols(.31, .65, .28) #초록색 MiddleGreen \033[0m ", '\n')
cat("\033[1;32m mycols(.98, .48, .31) #Salmon \033[0m ", '\n')
cat("\033[1;32m mycols(.3, .05, .6) #보라색 \033[0m ", '\n')
cat("\033[1;32m mycols(.20, .30, .80) #파랑색 \033[0m ", '\n')
cat("\033[1;32m mycols(.25, .41, .88) #RoyalBlue \033[0m ", '\n')
cat("\033[1;32m mycols(0, 0, .55) #DarkBlue \033[0m ", '\n')
cat("\033[1;32m mycols(.39, .58, .93) #CornflowerBlue \033[0m ", '\n')
cat("\033[1;32m mycols(.275, .51, .706) #SteelBlue \033[0m ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## 막대그래프: 변수 1개 ------------------------- \033[0m ", '\n')
cat(" graphics.off()  ", '\n')
cat(" library(aj412s2); library(ggplot2); library(dplyr)  ", '\n')
cat(" df<-BasicData  ", '\n')
cat(" df<-comp22(df)  ", '\n')
cat("   ", '\n')
cat(" # 1. geom_bar()의 stat = 'count'를 사용하면 각 범주의 빈도를 y축 값으로 사용  ", '\n')
cat(" # 2. stat = 'identity'를 사용하면 x-y값으로 막대그래프 작성  ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## 막대그래프: 변수1 / 변수1의 갯수 ------------------- \033[0m ", '\n')
cat(" ggplot(data=df, aes(x=conv)) +   ", '\n')
cat("   geom_bar(fill='steelblue', stat='count', width=0.5, alpha=0.7) +   ", '\n')
cat("   mytheme + labs(x='편의성 정도', y='빈도수')  ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## 막대그래프: 변수1 / 변수2의 평균 ------------------- \033[0m ", '\n')
cat(" # 예제2: stat='identity'  ", '\n')
cat(" graphics.off()  ", '\n')
cat(" tmp1<-df%>%group_by(gender)%>%summarize(평균=mean(conv) )  ", '\n')
cat(" head(tmp1)  ", '\n')
cat(" tmp1$gender<-as.factor(tmp1$gender)  ", '\n')
cat("   ", '\n')
cat(" mycols(0.1, 0.25, 0.02)  ", '\n')
cat(" ggplot(data=tmp1, aes(x=gender, y=평균)) +   ", '\n')
cat("   geom_bar(fill='#1A4005C6', stat='identity', width=0.3, alpha=.7) +   ", '\n')
cat("   mytheme + labs(x='성별', y='평균') + ylim(0, 3)  ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## 막대그래프: 변수1 / 변수2의 평균 -------------------  \033[0m ", '\n')
cat(" graphics.off()  ", '\n')
cat(" library(aj412s2); library(ggplot2)  ", '\n')
cat(" Adata<-BasicData  ", '\n')
cat(" tmp2<-Adata %>% group_by(nfamily) %>% summarize(소득평균=mean(inc))  ", '\n')
cat(" tmp2  ", '\n')
cat("   ", '\n')
cat(" ggplot(data=tmp2, aes(x=nfamily, y=소득평균)) +  ", '\n')
cat("   geom_bar(stat='identity', fill='#00BFFFFF', width=0.5, alpha=0.8) +   ", '\n')
cat("   mytheme +  ", '\n')
cat("   geom_text(aes(label = paste0( round(소득평균, 0), '만') ),  ", '\n')
cat("             vjust = 0.0, # 막대 상단에 위치. 중간위치는 10 정도  ", '\n')
cat("             color = 'black', size = 5) +  ", '\n')
cat("   labs(x='가구원수' , y='소득평균')  ", '\n')
cat("   ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## 막대그래프: 변수 3개 --------------------   \033[0m ", '\n')
cat(" graphics.off()  ", '\n')
cat(" library(ggplot2); library(dplyr)  ", '\n')
cat(" Adata<-StudyExhaust  ", '\n')
cat(" tmp3<-table(Adata$gpa, Adata$gender)  ", '\n')
cat(" tmp3<-as.data.frame(tmp3)  ", '\n')
cat(" tmp3  ", '\n')
cat(" colnames(tmp3)<-c('학점', '성별', 'freq')  ", '\n')
cat("   ", '\n')
cat(" # 성별에 따른 총 빈도 계산 (비율 계산을 위함)  ", '\n')
cat(" tmp3_summary <- tmp3 %>%  ", '\n')
cat("   group_by(성별) %>%  ", '\n')
cat("   mutate(total_freq = sum(freq)) %>%  ", '\n')
cat("   ungroup() %>%  ", '\n')
cat("   mutate(percentage = freq / total_freq * 100)  ", '\n')
cat("   ", '\n')
cat(" tmp3_summary  ", '\n')
cat("   ", '\n')
cat(" # 학점과 성별을 팩터로 변환 (ggplot2에서 순서대로 표시되도록)  ", '\n')
cat(" tmp3_summary$학점 <- factor(tmp3_summary$학점, levels = c(1, 2, 3, 4, 5))  ", '\n')
cat(" tmp3_summary$성별 <- factor(tmp3_summary$성별, levels = c(0, 1), labels = c('여성', '남성'))  ", '\n')
cat(" tmp3_summary  ", '\n')
cat("   ", '\n')
cat(" green_palette <- c('#D0F0C0', '#A0D090', '#70B060', '#409030', '#107000') # 예시 색상  ", '\n')
cat("   ", '\n')
cat(" ggplot(data=tmp3_summary, aes(x = 성별, y = percentage, fill = 학점)) +  ", '\n')
cat("   geom_bar(stat = 'identity', position = 'stack') +  ", '\n')
cat("   scale_fill_manual( values = green_palette, name = '학점') +  ", '\n')
cat("   labs(title = '성별에 따른 학점 비율', x = '성별', y = '비율 (%)' ) + mytheme +  ", '\n')
cat("   # 각 막대 위에 비율 텍스트 추가 (선택 사항)  ", '\n')
cat("   geom_text(aes(label = paste0(round(percentage, 1), '%')),  ", '\n')
cat("             position = position_stack(vjust = 0.5), # 막대 중앙에 위치  ", '\n')
cat("             color = 'black', size = 4)  ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## 위로 쌓기 + Freq --------------- \033[0m ", '\n')
cat(" tmp3  ", '\n')
cat(" tmp3$성별 <- factor(tmp3$성별, levels = c(0, 1), labels = c('여성', '남성'))  ", '\n')
cat(" my_palette <- c('#1A056655', '#1A05661C') # 예시 색상  ", '\n')
cat("   ", '\n')
cat(" ggplot(data=tmp3, aes(x=학점, y=freq, fill=성별)) +  ", '\n')
cat("   geom_bar(stat='identity', position='stack', col='black') +  ", '\n')
cat("   labs(title='Position=stack', x='성별', y='빈도수') + mytheme +  ", '\n')
cat("   scale_fill_manual( values = my_palette, name = '성별') +  ", '\n')
cat("   geom_text(aes(label = freq),  ", '\n')
cat("           position = position_stack(vjust = 0.5), # 막대 중앙에 위치  ", '\n')
cat("           color = 'black', size = 5)  ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## 막대그래프의 x축과 y축의 위치 변경하기 -------------  \033[0m ", '\n')
cat(" tmp3  ", '\n')
cat(" graphics.off() ", '\n')
cat(" tmp3$성별 <- factor(tmp3$성별, levels = c(0, 1), labels = c('여성', '남성'))  ", '\n')
cat(" ggplot(data=tmp3) +  ", '\n')
cat("   geom_bar(aes(x=reorder(학점, freq), y=freq, fill=성별),  ", '\n')
cat("            stat='identity', position='stack', col='black', width=0.5) +  ", '\n')
cat("   labs(title='Position=stack', x='빈도수', y='학점') + mytheme + coord_flip()  ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## 섬세한 막대그래프 그리기1  --------------------------  \033[0m ", '\n')
cat(" graphics.off()  ", '\n')
cat(" library(aj412s2); library(dplyr); library(ggplot2)  ", '\n')
cat("   ", '\n')
cat(" ## 연령과 소비지출 -------------- ", '\n')
cat(" Adata<-BasicData  ", '\n')
cat(" cn<-quantile(Adata$expend, c(.2, .4, .6, .8)) # 20%, 40%, ...의 소비지출  ", '\n')
cat(" cn  ", '\n')
cat(" Adata<-mkgroup(Adata, expend, cn) # g_expend 생성됨  ", '\n')
cat(" Bdata<-table(Adata$age, Adata$g_expend)  ", '\n')
cat(" df<-as.data.frame(Bdata)  ", '\n')
cat(" head(df)  ", '\n')
cat(" colnames(df)<-c('대표자연령', '소비지출', '빈도수')  ", '\n')
cat(" class_col(df)  ", '\n')
cat(" df$대표자연령<-as.character(df$대표자연령)  ", '\n')
cat(" df$소비지출<-as.character(df$소비지출)  ", '\n')
cat(" df  ", '\n')
cat(" # 그래프에 원하는 배열 순서대로  대표자연령에 A, B, C ...알파벳 포함  ", '\n')
cat(" # 알파벳을 않붙이면 가나다라..순서대로 배열됨  ", '\n')
cat(" # 연령대는 숫자이기 때문에 숫자 순서대로 정렬되므로 알파벳을 않붙여도 됨  ", '\n')
cat(" df  ", '\n')
cat(" df$대표자연령[df$대표자연령=='1']<-'<30대'  ", '\n')
cat(" df$대표자연령[df$대표자연령=='2']<-'<40대'  ", '\n')
cat(" df$대표자연령[df$대표자연령=='3']<-'<50대'  ", '\n')
cat(" df$대표자연령[df$대표자연령=='4']<-'<60대'  ", '\n')
cat(" df$대표자연령[df$대표자연령=='5']<-'<70대'  ", '\n')
cat(" df$대표자연령[df$대표자연령=='6']<-'>70대'  ", '\n')
cat("   ", '\n')
cat(" df$소비지출[df$소비지출=='1']<-'<20.8만원'  ", '\n')
cat(" df$소비지출[df$소비지출=='2']<-'<43.2만원'  ", '\n')
cat(" df$소비지출[df$소비지출=='3']<-'<48.6만원'  ", '\n')
cat(" df$소비지출[df$소비지출=='4']<-'<65.3만원'  ", '\n')
cat(" df$소비지출[df$소비지출=='5']<-'>65.3만원'  ", '\n')
cat("   ", '\n')
cat("\033[1;31m ##------------------------------------ \033[0m ", '\n')
cat(" mycols(.3, .1, .5)  ", '\n')
cat(" Adata<-StudyExhaust  ", '\n')
cat(" tmp3<-table(Adata$gpa, Adata$gender)  ", '\n')
cat(" tmp3<-as.data.frame(tmp3)  ", '\n')
cat(" tmp3  ", '\n')
cat(" colnames(tmp3)<-c('학점', '성별', 'freq')  ", '\n')
cat("   ", '\n')
cat(" ggplot(data=df) + theme_bw() +  ", '\n')
cat("   geom_bar(aes(x=대표자연령, y=빈도수, fill=소비지출),   ", '\n')
cat("            stat='identity', position='dodge', width=0.5 ) +  ", '\n')
cat("   scale_fill_manual(values = c( '<20.8만원' = '#4D1A801C',  ", '\n')
cat("                                 '<43.2만원' ='#4D1A8055',  ", '\n')
cat("                                 '<48.6만원'='#4D1A808E',  ", '\n')
cat("                                 '<65.3만원'='#4D1A80C6',  ", '\n')
cat("                                 '>65.3만원'='#4D1A80FF')) +  ", '\n')
cat("   # hjust지정없으면 맨 왼쪽에 배열  ", '\n')
cat("   theme(plot.title=element_text(hjust = 0.5)) +  ", '\n')
cat("   labs(x='대표자 연령', y='빈도수', title='소비지출액 분포') +  ", '\n')
cat("   theme(title=element_text(size= 30 , face='bold')) +  ", '\n')
cat("   # X축명(axis.title.x) 폰트 크기 + X축 숫자 크기(axis.text.x) 및 X축의 기울이기  ", '\n')
cat("   theme(axis.title.x = element_text(size= 25 ,face='bold')) +    ", '\n')
cat("   theme(axis.text.x=element_text(color='black', size=13, angle=-20, vjust=0.3)) +  ", '\n')
cat("   # Y축명(axis.title.y) 폰트 크기 + Y축 숫자 크기(axis.text.y)  ", '\n')
cat("   theme(axis.title.y = element_text(size= 25 ,face='bold')) +    ", '\n')
cat("   theme(axis.text.y=element_text(color='black', size=13)) +  ", '\n')
cat("   # Y축의 숫자를 3자리씩 끊어서 콤마를 표시  ", '\n')
cat("   scale_y_continuous(labels =scales:: comma) +    ", '\n')
cat("   # 범례의 타이틀 크기 및 범례 숫자 크기  ", '\n')
cat("   theme(legend.title = element_text(size = 15)) +  ", '\n')
cat("   theme(legend.text = element_text(size = 13))  ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## 섬세한 막대그래프 그리기2  ------------------  \033[0m ", '\n')
cat(" Adata<-StudyExhaust  ", '\n')
cat(" tmp3<-table(Adata$gpa, Adata$gender)  ", '\n')
cat(" tmp3<-as.data.frame(tmp3)  ", '\n')
cat(" tmp3  ", '\n')
cat(" colnames(tmp3)<-c('학점', '성별', 'freq')  ", '\n')
cat("   ", '\n')
cat(" tmp3$성별 <- factor(tmp3$성별, levels = c(0, 1), labels = c('여성', '남성'))  ", '\n')
cat("   ", '\n')
cat(" ggplot(data=tmp3, aes(x=학점, y=freq, fill=성별)) +  ", '\n')
cat("   theme_bw() +  ", '\n')
cat("   # 타이틀명 및 타이틀의 폰트 크기  ", '\n')
cat("   geom_bar(stat='identity', position='dodge', col='black') +  ", '\n')
cat("   labs(x='학점GPA', y='빈도수', title='성별에 따른 학점GPA') +  ", '\n')
cat("   theme(title=element_text(size= 20 , face='bold')) +  ", '\n')
cat("   # X축명(axis.title.x) 폰트 크기 + X축 숫자 크기(axis.text.x) 및 X축의 기울이기  ", '\n')
cat("   theme(axis.title.x = element_text(size= 15 ,face='bold')) +    ", '\n')
cat("   theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5)) +  ", '\n')
cat("   # Y축명(axis.title.y) 폰트 크기 + Y축 숫자 크기(axis.text.y)  ", '\n')
cat("   theme(axis.title.y = element_text(size= 15 ,face='bold')) +  ", '\n')
cat("   theme(axis.text.y=element_text(color='black', size=13)) +   ", '\n')
cat("   # Y축의 숫자를 3자리씩 끊어서 콤마를 표시  ", '\n')
cat("   scale_y_continuous(labels =scales:: comma) +    ", '\n')
cat("   # 범례의 타이틀 크기 및 범례 숫자 크기  ", '\n')
cat("   theme(legend.title = element_text(size = 15)) +  ", '\n')
cat("   theme(legend.text = element_text(size = 13)) +  ", '\n')
cat("   # 막대그래프의 색깔을 지정  ", '\n')
cat("   scale_fill_manual(values = c( '여성' = 'salmon', '남성' ='cyan4'))  ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## line graph의 색깔 지정하기  ----------------- \033[0m ", '\n')
cat(" library(aj412s2); library(dplyr); library(ggplot2)  ", '\n')
cat(" df<-openxlsx(file.choose())  ", '\n')
cat(" df  ", '\n')
cat("   ", '\n')
cat(" ggplot(df, aes(x = time, y = prob, color = 직업변화)) +  ", '\n')
cat("   geom_line(lwd=2, lty='dashed') + theme_bw() +  ", '\n')
cat("   scale_color_manual(values =  ", '\n')
cat("                        c( '제조->서비스' = 'blue',  ", '\n')
cat("                           '전기->서비스' = 'black',  ", '\n')
cat("                           '연구->서비스' = 'red')) +  ", '\n')
cat("   theme(title=element_text(size= 20 , face='bold')) +  ", '\n')
cat("   # X축명(axis.title.x) 폰트 크기 + X축 숫자 크기(axis.text.x) 및 X축의 기울이기  ", '\n')
cat("   theme(axis.title.x = element_text(size= 15 ,face='bold')) +    ", '\n')
cat("   theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5)) +  ", '\n')
cat("   # Y축명(axis.title.y) 폰트 크기 + Y축 숫자 크기(axis.text.y)  ", '\n')
cat("   theme(axis.title.y = element_text(size= 15 ,face='bold')) +  ", '\n')
cat("   theme(axis.text.y=element_text(color='black', size=13)) +   ", '\n')
cat("   labs(x='시간', y='확률', title='시간에 따른 직업변화')  ", '\n')
cat(" ", '\n')
cat("\033[1;31m ## dotchart 그리기  --------------------  \033[0m ", '\n')
cat(" graphics.off()  ", '\n')
cat(" library(aj412s2); library(dplyr); library(ggplot2); library(ggthemes)  ", '\n')
cat(" Adata<-BasicData  ", '\n')
cat(" colnames(Adata)  ", '\n')
cat(" re<-lm(expend~inc+nfamily+gender, data=Adata)  ", '\n')
cat("   ", '\n')
cat(" x<-c('소득', '가구원수', '성별')  ", '\n')
cat("   ", '\n')
cat(" # ols_pred 또는, lm_pred로 구한 값  ", '\n')
cat(" y<-c(569, 463, 456)  ", '\n')
cat("   ", '\n')
cat(" # 컬러를 구현하기 위한 독립변수와 대응되는 그룹명을 임의로 지정 ------- \033[0m ", '\n')
cat(" group<-c('A1', 'A2', 'A3')  ", '\n')
cat(" dataset<-cbind(x, y, group)  ", '\n')
cat(" dataset<-as.data.frame(dataset)  ", '\n')
cat(" dataset$y<-as.numeric(dataset$y)  ", '\n')
cat(" dataset$group<-as.factor(dataset$group)  ", '\n')
cat("   ", '\n')
cat(" dataset$color[dataset$group=='A1']<-'blue'  ", '\n')
cat(" dataset$color[dataset$group=='A2']<-'red'  ", '\n')
cat(" dataset$color[dataset$group=='A3']<-'steelblue'  ", '\n')
cat("   ", '\n')
cat(" dotchart(dataset$y,  ", '\n')
cat("          labels=dataset$x,  ", '\n')
cat("          groups=dataset$group,  ", '\n')
cat("          gcolor='black',  ", '\n')
cat("          color=dataset$color,  ", '\n')
cat("          pch=19,  ", '\n')
cat("          cex=1.3,  ", '\n')
cat("          cex.main=1.5,  ", '\n')
cat("          main='독립변수 변화에 따른 소비지출 변화',  ", '\n')
cat("          xlab='소비지출'  ", '\n')
cat(" )  ", '\n')
cat("   ", '\n')
cat("   ", '\n')
cat(" p <- dotchart(dataset$y,  ", '\n')
cat("               labels=dataset$x,  ", '\n')
cat("               groups=dataset$group,  ", '\n')
cat("               gcolor='black',  ", '\n')
cat("               color=dataset$color,  ", '\n')
cat("               pch=19,  ", '\n')
cat("               cex=1.3,  ", '\n')
cat("               cex.main=1.5,  ", '\n')
cat("               main='독립변수 변화에 따른 소비지출 변화',  ", '\n')
cat("               xlab='소비지출'  ", '\n')
cat(" )  ", '\n')
cat("   ", '\n')
cat(" p + abline(v=464, lty = 'dashed', lwd=2, col = 'blue') +  ", '\n')
cat("   text(x = 464, y = 2, labels = 'Base Line', pos = 4, col = 'blue', srt = 90)  ", '\n')
cat("   ", '\n')
cat("\033[1;32m ## 파이차트 그리기 ------------------  \033[0m ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## piechart1: 대표자 연령 분포 -------- \033[0m ", '\n')
cat(" graphics.off()  ", '\n')
cat(" library(ggplot2); library(aj412s2); library(dplyr)  ", '\n')
cat(" Adata<-BasicData  ", '\n')
cat(" Adata<-table(Adata$age)  ", '\n')
cat(" df<-as.data.frame(Adata)  ", '\n')
cat(" colnames(df)<-c('대표자연령', '빈도수')  ", '\n')
cat(" df$대표자연령<-as.numeric(df$대표자연령)  ", '\n')
cat("   ", '\n')
cat(" # 그래프에 원하는 배열 순서대로  점포명 앞에 A, B, C ...알파벳 포함하기  ", '\n')
cat(" # 알파벳을 않붙이면 가나다라..순서대로 배열됨  ", '\n')
cat(" # 그런데, 연령대는 숫자이기 때문에 숫자 순서대로 정렬되므로 알파벳을 않붙여도 됨", '\n')
cat("   ", '\n')
cat(" class_col(df)  ", '\n')
cat(" df  ", '\n')
cat("   ", '\n')
cat(" df$대표자연령[df$대표자연령==1]<-'20대'  ", '\n')
cat(" df$대표자연령[df$대표자연령==2]<-'30대'  ", '\n')
cat(" df$대표자연령[df$대표자연령==3]<-'40대'  ", '\n')
cat(" df$대표자연령[df$대표자연령==4]<-'50대'  ", '\n')
cat("   ", '\n')
cat(" round(df$빈도수/sum(df$빈도수)*100, 0)  ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## x에 변수명 입력이 없음  -------------   \033[0m ", '\n')
cat(" ggplot(df, aes(x = '', y=빈도수, fill = 대표자연령)) +  ", '\n')
cat("   geom_bar(stat='identity', width=1) +  ", '\n')
cat("   coord_polar(theta = 'y', start=0) +  ", '\n')
cat("   scale_fill_manual(values = c('20대'='#4D1A80FF', '30대'='#4D1A80C6', '40대'='#4D1A808E', '50대' = '#4D1A8055')) + ", '\n')
cat("   theme_void() + ", '\n')
cat("   ggtitle('대표자 연령의 분포') + ", '\n')
cat("   geom_col(color = 'black') +  ", '\n')
cat(" ", '\n')
cat("   ## position_fill vs position_stack  ", '\n')
cat("   # 차트 내부 숫자 크기를 10으로 하는 경우  ", '\n')
cat("   geom_text(aes(label = c('20대: 22%', '30대: 28%', '40대: 31%', '50대: 19%')),  ", '\n')
cat("             position = position_stack(vjust = 0.5), size=5, fontface = 2) +  ", '\n')
cat("   labs(x='', y='') +  ", '\n')
cat("   #차트 제목 위치를 우측으로 옮기기  ", '\n')
cat("   theme(plot.title=element_text(hjust = 0.5)) +  ", '\n')
cat("   #차트 제목 크기를 조정하기  ", '\n')
cat("   theme(plot.title=element_text(size = 25.3)) +  ", '\n')
cat("   #차트 제목 색깔을 조정하기  ", '\n')
cat("   theme(plot.title=element_text(colour = 'black')) +  ", '\n')
cat("   #차트 legend범례 크기를 18로 하는 경우  ", '\n')
cat("   theme(legend.text = element_text(size = 18)) +  ", '\n')
cat("   theme(legend.title = element_text(size = 18))  ", '\n')
cat("   ", '\n')
cat("\033[1;31m ## piechart2: 대표자 연령 분포 ----------- \033[0m ", '\n')
cat(" graphics.off() ", '\n')
cat(" library(ggplot2); library(aj412s2)  ", '\n')
cat(" mtcars$car = row.names(mtcars)  ", '\n')
cat(" # 자동차별 mpg 그래프  ", '\n')
cat(" mtcars  ", '\n')
cat(" p<-ggplot(mtcars, aes(x=car, y=mpg, fill=mpg)) +  ", '\n')
cat("   geom_histogram(stat='identity', width=0.8 ) +    ", '\n')
cat("   theme_light() +   ", '\n')
cat("   scale_fill_gradient(low='red', high='white', limits=c(5,40)) +  ", '\n')
cat("   theme(axis.title.y=element_text(angle=0)) +    ", '\n')
cat("   theme(axis.text.x = element_text(angle=45, vjust = 1, hjust=1))  ", '\n')
cat("   ", '\n')
cat(" print(p)  ", '\n')
cat("\033[1;31m ## mpg값의 범위가 5~40이므로 lmits을 4~50으로 설정함  \033[0m ", '\n')
cat("   ", '\n')
cat(" p + coord_polar()  ", '\n')
cat("   ", '\n')
cat(" p + coord_polar() + aes(x=reorder(car, mpg)) +  ", '\n')
cat("   theme(axis.text.x = element_text(angle=-20))  ", '\n')
cat("   ", '\n')

}

}


