e_graph1<-function(explaining=0){

if(explaining==0) {
cat("   ", '\n')
cat("\033[1;33m# 백그라운드를 만들어 지정하기 -------- \033[0m ", '\n')
cat("\033[1;33m## 데이터프레임 -------\033[0m ", '\n')
cat(" df<-data.frame(  ", '\n')
cat("     id=c(1, 2, 3, 4, 5, 6, 7, 8),  ", '\n')
cat("     day=c('Mon', 'Mon', 'Tue', 'Tue', 'Tue', 'Wed', 'Wed', 'Wed'),  ", '\n')
cat("     gender=c('남','여','여','남','남','여','남','여'),  ", '\n')
cat("     expend=c(800, 1400, 2000, 1600, 1400, 1600, 1340, 1900),  ", '\n')
cat("     no.items=c(4, 3, 5, 10, 13, 6, 22, 9)  )  ", '\n')
cat("   ", '\n')
cat(" tmp<-table(df$day, df$gender)  \033[1;33m# 범주형x범주형: 빈도수가 계산됨 \033[0m ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("  tmp<-data.frame( t(tmp) ) ", '\n')
cat("  colnames(tmp)<-c('Gender', 'Day', 'freq') ", '\n')
cat("  mycols(.01, .0, .01)  ", '\n')
cat("   ", '\n')
cat("  library(ggplot2) ", '\n')
cat("    ", '\n')
cat(" mytheme <- theme(  ", '\n')
cat("     plot.background = element_rect(fill = "#1A00331C", color = 'black', size = 1), # 전체 플롯 배경 색("#1A00331C")  ", '\n')
cat("     panel.background = element_rect(fill = 'white', color = 'gray'), # 그래프 영역 배경 색  ", '\n')
cat("     panel.grid.major = element_line(color = '#0300031C', size = 0.5), # 주요 그리드 선  ", '\n')
cat("     panel.grid.minor = element_line(color = 'gray', size = 0.25, linetype = 'dashed'), # 보조 그리드 선  ", '\n')
cat("     panel.grid = element_line(color = 'black', size = 0.5), # 전체 그리드 선 색과 두께  ", '\n')
cat("     axis.title.x = element_text(size = 18, color = 'black', hjust=0.5), # X축 제목 스타일 ", '\n')
cat("     axis.title.y = element_text(size = 18, color = 'black', hjust=0.5), # Y축 제목 스타일 ", '\n')
cat("     plot.title = element_text(size = 20, color = 'black', hjust = 1, vjust = 2, face = 'bold'), # Title 조정 ", '\n')
cat("     plot.margin = margin(t = 20, r = 10, b = 10, l = 10), # Title 조정 ", '\n')
cat("     legend.text = element_text(size = 10), ", '\n')
cat("     legend.title = element_text(size = 10), ", '\n')
cat("     legend.position = 'right'  ## legend.position = 'none' OR 'bottom' ", '\n')
cat("    )  ", '\n')
cat("   ", '\n')
cat("  p1<-ggplot(tmp, aes(x=Day, y=freq, fill=Gender)) +  ", '\n')
cat("     geom_bar(stat='identity', position='dodge', width=0.5 ) + # width는 막대그래프 넓이 ", '\n')
cat("     scale_fill_manual(values = c('#4D1A6655', '#4D1A66FF')) +  ", '\n')
cat("     theme(axis.text.x=element_text(angle=-40)) +  ", '\n')
cat("     labs(title='성별과 요일', x='요일', y='빈도수')  ", '\n')
cat("  p1 + mytheme   ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("  year <- c(2021, 2022, 2023, 2024) ", '\n')
cat("  gdp <- c(130, 160, 140, 150) ", '\n')
cat("  unemployment <- c(0.05, 0.06, 0.055, 0.065) ", '\n')
cat("  data <- data.frame(year, gdp, unemployment) ", '\n')
cat("   ", '\n')
cat("  # 보조 축을 위한 실업률 스케일 조정 (예: 실업률을 2000배 확대하여 시각화) ", '\n')
cat("  scale_factor <- 2000  # 큰값/작은값 = mean(data$gdp)/mean(data$unemployment) ", '\n')
cat("  p2<-ggplot(data, aes(x = year)) + ", '\n')
cat("     geom_line(aes(y = gdp, color = 'GDP'), size = 1.2) + ", '\n')
cat("     geom_line(aes(y = unemployment * scale_factor, color = 'Unemployment Rate'), size = 1.2) + ", '\n')
cat("     scale_y_continuous(name = 'GDP', sec.axis = sec_axis(~./scale_factor, name = 'Unemployment Rate')) + ", '\n')
cat("     scale_color_manual(values = c('GDP' = 'blue', 'Unemployment Rate' = 'red')) + ", '\n')
cat("     labs(x = 'Year', color = 'Indicator', title = 'GDP와 실업률 추이') ", '\n')
cat(" p2 + mytheme   ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m# Panel Data --------\033[0m    ", '\n')
cat("  library(gplots); library(plm)    ", '\n')
cat("  Grunfedl<-data(package='plm', 'Grunfeld')    ", '\n')
cat("  Gdata<-Grunfeld    ", '\n')
cat("  plotmeans(Gdata$inv~Gdata$firm)   ", '\n')
cat("  plotmeans(Gdata$inv~Gdata$year)   ", '\n')
cat("    ", '\n')
cat("\033[1;31m# 시계열분석 --------\033[0m ", '\n')
cat("  library(forecast) ", '\n')
cat("  AccountBalance <- ts(AccountBalance, start=c(2015,1), frequency=4) ", '\n')
cat("  \033[1;32m# autoplot \033[0m  autoplot(AccountBalance[ ,c('export','profit')], facets=TRUE )  # forecast패키지  \033[0m", '\n') 
cat("  \033[1;32m# ggseasonplot \033[0m  ggseasonplot(AccountBalance[,'import'], year.labels = TRUE, year.labels.left=TRUE)  # forecast패키지  \033[0m", '\n')
cat("  \033[1;32m# ggsubseriesplot \033[0m  ggsubseriesplot(AccountBalance[,'export'])  # forecast패키지  \033[0m", '\n')
cat("  ", '\n')

cat("\033[1;31m# 히스토그램 with jmv and ggplot -------------------\033[0m ", '\n')
cat("  Adata<-interest ", '\n')
cat("  jmv::descriptives(data = interest, vars = LoanInterest, hist=TRUE, dens=TRUE) ", '\n')
cat("  ggplot(data=Adata, aes(x=LoanInterest)) + geom_histogram(bins=40) ", '\n')
cat("   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("\033[1;31m# -- geom_point산포도 with ggplot -------\033[0m ", '\n')
cat("  library(dplyr); library(aj412s); library(ggplot2); library(ggthemes) ", '\n')
cat("  Adata<-KoreaMacro ", '\n')
cat("  Adata<-as.data.frame(Adata) ", '\n')
cat("   ", '\n')
cat("\033[1;31m## geom_point의 alpha는 포인트의 투명도를 지정 \033[0m ", '\n')
cat("  ggplot(data=Adata, aes(x=yearmonth, y=kospi)) + geom_point(size=3, alpha=0.3, col='steelblue') + ", '\n')
cat("      geom_line(col='black') + ", '\n')
cat("      labs(x='시간', y='코스피지수', title='코스피지수의 변화', " , '\n')
cat("      subtitle='코스피 인덱스의 시간에 따른 변화 추이 분석',   " , '\n')
cat("      caption='Source: Account' ) ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))

cat(" \033[1;31m# -- geom_line직선 with ggplot -------\033[0m ", '\n')
cat(" \033[1;31m# -- linetype : blank, solid, dashed, dotted, dotdash, longdash, twodash -------\033[0m ", '\n')
cat("   ", '\n')
cat(" \033[1;31m# KoreaMacro 변수명 재정의  \033[0m ", '\n')
cat("  colnames(Adata)<-c('index', 'yearmonth', 'currency', 'cd91', 'bond3yr', 'kospi', 'surplus') ", '\n')
cat("   ", '\n')
cat("\033[1;31m# 직선 그리기를 위한 데이터작업 시작 --------\033[0m ", '\n')
cat("  Adata<-mkdate_form(Adata, 2)  ", '\n')
cat("  colnames(Adata)[8]<-'yearmonth2' ", '\n')
cat("  Adata$year<-substring(Adata$yearmonth2, 1,4) ", '\n')
cat("  Adata$month<-substring(Adata$yearmonth2, 6,7) ", '\n')
cat("  Adata$year<-as.numeric(Adata$year) ", '\n')
cat("  Adata$month<-as.numeric(Adata$month) ", '\n')
cat("  코스피<-Adata %>% group_by(year) %>% summarize(KOSPI평균=mean(kospi))  ", '\n')

cat("\033[1;31m# 직선 그리기를 위한 데이터작업 끝남 --------\033[0m ", '\n')

cat("  ", '\n')
cat("  p <- ggplot(data=코스피, aes(x=year, y=KOSPI평균)) +  ", '\n')
cat("  \033[1;31m직선 셋업\033[0m  geom_line(group=1, col='red', linewidth=1) + ", '\n')
cat("  \033[1;31m점 셋업\033[0m    geom_point(col='red', size=3.0) + ", '\n')
cat("  \033[1;31my값 표시\033[0m   geom_text( data=코스피, aes(y=KOSPI평균, label = round(KOSPI평균,0), vjust=-1, size=4) ) + ", '\n')
cat("  \033[1;31mx축값 표시\033[0m theme(axis.text.x=element_text(color='black', size=13, angle=-40, vjust=-.5)) + ", '\n')
cat("  \033[1;31my축값 표시\033[0m theme(axis.text.y=element_text(color='black', size=13)) + ", '\n')
cat("  \033[1;31my축값 자리수\033[0m scale_y_continuous(labels =scales:: comma) + ", '\n')
cat("  \033[1;31m제목 크기\033[0m  theme(title=element_text(size= 30 , face='bold')) + ", '\n')
cat("  \033[1;31my축명크기\033[0m  theme(axis.title.y = element_text(size= 25 ,face='bold')) + ", '\n')
cat("  \033[1;31mx축명크기\033[0m  theme(axis.title.x = element_text(size= 25 ,face='bold')) + ", '\n')
cat("  \033[1;31mxy축/제목 타이틀\033[0m labs(x='연도', y='연간 코스피평균', title='연도별 코스피평균') + ", '\n')
cat("  \033[1;31m범례 삭제\033[0m theme(legend.position = 'none') ", '\n')
cat("  \033[1;32m그래프출력\033[0m print(p) ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m# 막대그래프 with ggplot -------- \033[0m ", '\n')
cat("\033[1;32m# X축을 factor로 지정해야만 X값이 지정한 순서대로 출력됨  \033[0m ", '\n')
cat("\033[1;32m# 막대그래프 오름차순: ggplot(data=경상수지, aes(x=reorder(year, -경상수지평균), y=경상수지평균)) ... )\033[0m ", '\n')
cat("\033[1;32m# 막대그래프 내림차순: ggplot(data=경상수지, aes(x=reorder(year, 경상수지평균), y=경상수지평균)) ... )\033[0m ", '\n')
cat("   ", '\n')
cat("library(ggplot2) ", '\n')
cat("  xx <- c('30세이하', '30대', '40대', '50대', '60세이상') ", '\n')
cat("  yy <- c(90.6, 81.5, 73.2, 69.4, 65) ", '\n')
cat("  Adata<-data.frame(xx,yy) ", '\n')
cat("\033[1;31m# X축을 factor로 지정해야만 X값이 지정한 순서대로 출력된다 \033[0m ", '\n')
cat("  Adata$xx <- factor(Adata$xx,levels=c('30세이하','30대','40대','50대','60세이상')) ", '\n')
cat("   ", '\n')
cat("  ggplot(data=Adata, aes(x=xx, y=yy, fill='steelblue')) +  ", '\n')
cat("  \033[1;32m셋업\033[0m       theme_bw() +  ", '\n')
cat("  \033[1;32m셋업\033[0m       geom_bar(stat='identity', col='black', width=0.7) +  ", '\n')
cat("  \033[1;32mX값\033[0m        theme(axis.text.x=element_text(size= 16 , angle=-40) ) + ", '\n')
cat("  \033[1;32mY값\033[0m        theme(axis.text.y=element_text(size= 16) ) + ", '\n')
cat("  \033[1;32mY값 자리수\033[0m scale_y_continuous(labels =scales:: comma) + ", '\n')
cat("  \033[1;32m제목\033[0m       labs(title='연도별 경상수지', x='연도', y='경상수지') + ", '\n')
cat("  \033[1;32m제목 크기\033[0m  theme(title=element_text(size=26 , face='bold')) + ", '\n')
cat("  \033[1;32mX축명크기\033[0m  theme(axis.title.x = element_text(size= 20 , face='bold')) + ", '\n')
cat("  \033[1;32mY축명크기\033[0m  theme(axis.title.y = element_text(size= 20 , face='bold')) + ", '\n')
cat("  \033[1;32m막대숫자\033[0m   geom_text(data=Adata, aes(y=yy, label = round(yy, 0) , vjust=-1, size=15) ) + ", '\n')
cat("  \033[1;32m범례삭제\033[0m   theme(legend.position = 'none') + ", '\n')
cat("  \033[1;32mY축범위\033[0m    ylim(0, 100)  ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat("\033[1;31m# facet_wrap의 활용 --------\033[0m ", '\n')
cat("  발<-c(235,222,235, 241,251,226, 274,282,291, 260,272,282) ", '\n')
cat("  키<-c(142,163,163, 165,171,167, 174,179,161, 187,189,178) ", '\n')
cat("  성별<-c('남','남','남', '남','남','남', '여','여','여', '여','여','여') ", '\n')
cat("  Adata <- as.data.frame( cbind(발, 키, 성별)) ", '\n')
cat("  p <- ggplot(Adata, aes(x=발, y=키) ) + ", '\n')
cat("        geom_point(col='blueviolet', size=2, alpha=0.4) +", '\n')
cat("        labs(x='발크기', y='신장', title='성별에 따른 발크기와 신장') +", '\n')
cat("        facet_wrap(~성별) ", '\n')
cat("  ", '\n')

}}