#e_kosis

e_kosis<-function(explaining=0){
if(explaining==0) {
cat("    ", '\n')
cat(" \033[1;36m##------------------------------------------------------ \033[0m", '\n' )
cat("    ", '\n')
cat("# apkey 다운로드 받는 곳 ", '\n')
cat("# https://kosis.kr/openapi/ ", '\n')
cat("    ", '\n')
cat("# KOSIS자료 Code Book ", '\n')
cat("# https://kosis.kr/openapi/devGuide/devGuide_0101List.do ", '\n')
cat("  ", '\n')
cat(" \033[1;36m##------------------------------------------------------ \033[0m", '\n' )
cat("    ", '\n')
cat("   library(kosis)  ", '\n')
cat("    ", '\n')
cat("   kosis.setKey(apiKey='당신의 API값을 입력하세요')   ", '\n')
cat("    ", '\n')
cat("#  MDE3ZDM1M2Y0MWIxELCA999NzI5OGIzZGExShimBIX777NmM1NWIzNTNlMjA=   ", '\n')
cat("  ", '\n')
cat("#  orgIds = 조직 ID ", '\n')
cat("#  prdSe = 수록주기: D(일), M, Q, H(3월), Y(년) ", '\n')
cat(" ", '\n')
cat(" kosis데이터 <- getStatData(   ", '\n')
cat("   orgId = '',  ", '\n')
cat("   tblId = '',  ", '\n')
cat("   prdSe = '',  ", '\n')
cat("   itmId = '',  ", '\n')
cat("   newEstPrdCnt = 숫자입력.따옴표 없음, ", '\n')
cat("   startPrdDe='', ", '\n')
cat("   endPrdDe='', ", '\n')
cat("   objL1='', ", '\n')
cat("   objL2='', ", '\n')
cat("   objL3='' ", '\n')
cat(" ) ", '\n')
cat(" \033[1;36m## Data Format의 변경 -------------------- \033[0m", '\n' )
cat("   data=data.frame( ", '\n')
cat("     V1=c('서울', '서울', '서울','서울', '서울', '서울', '경기도', '경기도', '경기도','경기도', '경기도', '경기도'),    ", '\n')
cat("     V2=c('노동','노동','노동', '광업','광업','광업','노동','노동','노동', '광업','광업','광업' ),    ", '\n')
cat("     V3=c(2023, 2022, 2021, 2023, 2022, 2021, 2023, 2022, 2021,2023, 2022, 2021),    ", '\n')
cat("     V4=c(4433, 4444, 4455, 4466, 4488, 4499, 8833, 8844, 8855, 8866, 8888, 8899) ", '\n')
cat("   ) ", '\n')
cat(" \033[1;36m## ---------------------------------------- \033[0m", '\n' )
cat("  ## R을 사용해 위 데이터셋을 재배열하는 명령문 --- ", '\n')
cat("   library(tidyr); library(dplyr)   ", '\n')
cat("   # wide format으로 변환   ", '\n')
cat("   # data91 <- data %>% mutate(분류 = paste(V1, V2, sep = '_' ) )  ", '\n')
cat("   # data92 <- data91 %>% select(분류, V1, V3, V4) ", '\n')
cat("   ", '\n')
cat("     data2 <- data %>% pivot_wider( ", '\n')
cat("        names_from = V2, ", '\n')
cat("        values_from = V4 ", '\n')
cat("        ) ", '\n')
cat("       ", '\n')
cat("   write.csv(data2, 'data2.csv', fileEncoding='EUC-KR' ) ", '\n')
cat("   ", '\n')
}
}
