e_widelong<-function(explaining=0){
if(explaining==0) {
cat("    ", '\n')
cat("  library(aj412s2); library(tidyr); library(dplyr)   ", '\n')
cat("    ", '\n')
cat("  면적명 <- c('녹지면적', '도시면적', '도로면적', '녹지면적', '도시면적', '도로면적')  ", '\n')
cat("  행정명 <- c('가락1동', '가락1동', '가락1동','가락2동', '가락2동', '가락2동')  ", '\n')
cat("  면적 <- c(10, 12, 30, 21, 53, 66)  ", '\n')
cat("    ", '\n')
cat("  df<-data.frame(cbind(면적명, 행정명, 면적))  ", '\n')
cat("    ", '\n')
cat("  # 데이터 변형 ----------  ", '\n')
cat("\033[1;33m  df_wide <- df %>%  \033[0m", '\n')
cat("    pivot_wider(  ", '\n')
cat("      id_cols = 행정명,  ", '\n')
cat("      names_from = 면적명,  ", '\n')
cat("      values_from = 면적  ", '\n')
cat("    )  ", '\n')
cat("    ", '\n')
cat("\033[1;33m  df_long <- df_wide %>%    \033[0m", '\n')
cat("    pivot_longer(  ", '\n')
cat("      cols = c('녹지면적', '도시면적', '도로면적'),  ", '\n')
cat("      names_to = '면적명',  ", '\n')
cat("      values_to = '면적'  ", '\n')
cat("    )  ", '\n')
cat("    ", '\n')
}}