e_widelong<-function(explaining=0){
if(explaining==0) {
cat("    ", '\n')
cat("\033[1;35m  # 가상의 데이터 만들기 ----------  \033[0m", '\n')
cat("  library(aj412s2); library(dplyr); library(tidyr) ", '\n')
cat("   ", '\n')
cat("  id<-c('수원시', '수원시', '수원시', '수원시', '용인시', '용인시', '성남시', '성남시', '성남시') ", '\n')
cat("  useless<-c(11, 22, 33, 44, 55, 66, 77, 88, 99) ", '\n')
cat("  type<-c('주거', '상업', '공업', '녹지', '주거', '공업', '상업', '공업', '녹지') ", '\n')
cat("  area<-c(11, 12, 14, 15, 23, 25, 34, 35, 39) ", '\n')
cat("  df<-data.frame(cbind(id, type, area, useless))  ", '\n')
cat("  df$area<-as.numeric(df$area) \033[1;35m  # area의 데이터를 숫자로 지정 \033[0m ", '\n')
cat("   ", '\n')
cat("  df<-sel22(df, id, type, area) \033[1;35m # df에서 id, type, area만 솎아내기  \033[0m  ", '\n')
cat("   ", '\n')
cat("\033[1;35m  # 데이터 변형 ----------  \033[0m", '\n')
cat("   ", '\n')
cat("\033[1;33m  # CASE 1 ---------------------- \033[0m", '\n')
cat("  df_wide <- df %>%  ", '\n')
cat("    pivot_wider(    ", '\n')
cat("        id_cols = id, ", '\n')
cat("        names_from = type, ", '\n')
cat("        values_from = area  ", '\n')
cat("        )  ", '\n')
cat("   ", '\n')
cat("  df_wide[is.na(df_wide)]<-0 ", '\n')
cat("        ", '\n')
cat("  mkcsv(df_wide, 'df_wide면적.csv')  \033[1;35m  # df_wide 데이터를 csv파일로 저장 \033[0m ", '\n')
cat("   ", '\n')
cat("\033[1;33m  # CASE 2 ---------------------- \033[0m", '\n')
cat("  df_long <- df_wide %>%  ", '\n')
cat("    pivot_longer(    ", '\n')
cat("        cols = c('주거', '상업', '공업', '녹지'),    ", '\n')
cat("        names_to = 'type', ", '\n')
cat("        values_to = 'area'   ", '\n')
cat("  	  )    ", '\n')
cat("   ", '\n')
cat("  df_long[is.na(df_long)]<-0   ", '\n')
cat("  mkcsv(df_long, 'df_long면적.csv')  \033[1;35m  # df_long 데이터를 csv파일로 저장 \033[0m  ", '\n')
cat("   ", '\n')
cat("\033[1;33m  # CASE 3 ---------------------- \033[0m", '\n')
cat("  df_면적합계<- df %>% group_by(id) %>% summarize(면적합계=sum(area, na.rm=T)) ", '\n')
cat("  mkcsv(df_면적합계, 'df_sum면적.csv')  \033[1;35m  # df_면적합계 데이터를 csv파일로 저장 \033[0m  ", '\n')
cat("   ", '\n')
cat("\033[1;33m  # CASE 4 ---------------------- \033[0m", '\n')
cat("  df_면적평균<- df %>% group_by(id) %>% summarize(면적평균=mean(area, na.rm=T)) ", '\n')
cat("  mkcsv(df_면적평균, 'df_mean면적.csv') \033[1;35m  # df_면적평균 데이터를 csv파일로 저장 \033[0m   ", '\n')
cat("   ", '\n')
cat("\033[1;33m  # NOTE: merging two data sets ------------- \033[0m", '\n')
cat("  df3 <- merge(df1, df2, by='id', all=T) ", '\n')
cat("   ", '\n')
}}